
name: Container Build

on:
  push:
    paths:
      - 'context/**'
      - '.github/workflows/ci.yml'
    branches:
      - '**'
    tags:
      - 'v*.*'

env:
  DOCKER_REPO: tomeichlersmith/hps-env

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test_tag: ${{steps.generate_tag.outputs.test_tag}}
    defaults:
      run:
        shell: bash
    steps:
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Cache Docker Layers on GitHub
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: Get Build Context
      uses: actions/checkout@v2
    -
      name: Determine Image Tags
      id: generate_tag
      run: |
          _tag=noop
          _retag=noop
          _test_tag=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # if pushing a git tag ==> get the git tag for the docker tag
            _tag=${GITHUB_REF#refs/tags/}
            echo "Checking for already built commit ${GITHUB_SHA::8}"
            if wget -q https://registry.hub.docker.com/v1/repositories/${DOCKER_REPO}/tags -O - | grep -q ${GITHUB_SHA::8}; then
              _retag=sha-${GITHUB_SHA::8}
            fi
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            # pushing to a branch ==> docker tag is branch name
            #   if branch name is default_branch, docker tag is 'edge'
            _tag=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$_tag" ]; then
              _tag=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            # pull request branch ==> docker tag is pr number
            _tag=pr-${{ github.event.number }}
          fi
          _push_tags="${DOCKER_REPO}:${_tag}"
          if [[ $_tag =~ ^v[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            # latest docker tag is latest version built matching the format v<1-3 digis>.<1-3 digis>
            _push_tags="$_push_tags,${DOCKER_REPO}:latest"
          elif [ "${{ github.event_name }}" = "push" ]; then
            # on push actions, tag with sha of GITHUB as well
            _push_tags="$_push_tags,${DOCKER_REPO}:sha-${GITHUB_SHA::8}"
            _test_tag="sha-${GITHUB_SHA::8}" 
          fi
          echo "Generated Tags: ${_push_tags}"
          echo "Re-Tag: ${_retag}"
          echo ::set-output name=push_tags::${_push_tags}
          echo ::set-output name=retag::${_retag}
          echo ::set-output name=test_tag::${_test_tag}
    -
      name: Build the Image
      if: ${{contains(steps.generate_tag.outputs.retag,'noop')}}
      uses: docker/build-push-action@v2
      with:
        context: context
        file: context/Dockerfile
        push: true 
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: ${{ steps.generate_tag.outputs.push_tags }}
    -
      name: Just Re-Tag an Already Built Image
      if: ${{steps.generate_tag.outputs.retag != 'noop'}}
      run: |
        _retag=${DOCKER_REPO}:${{steps.generate_tag.outputs.retag}}
        _newtags=${{steps.generate_tag.outputs.push_tags}}
        docker pull ${_retag}
        for t in ${_newtags//,/ }; do
          docker tag ${_retag} ${t}
          docker push ${t}
        done
